# Generated by Django 5.2.2 on 2025-07-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='link',
            field=models.URLField(default='https://127.0.0.1:8000/haberler/', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='published_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
