# Generated by Django 5.2.2 on 2025-07-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0002_bulletin_link_alter_bulletin_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
