# Generated by Django 5.2.2 on 2025-07-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0003_alter_bulletin_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='link',
            field=models.URLField(),
        ),
    ]
