# Generated by Django 5.2.2 on 2025-07-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0004_alter_bulletin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
